batch_size: 16
test_IDs_fn: "${oc.env:DATA_SPLITS_DIR}/test_rainformer_202324_avg001mm_9x9y.npy"
checkpoint_path: "${oc.env:GENERAL_MODEL_DIR}/train_rainformer_9x9_consistent_data/epoch26-loss8224.1187.ckpt"
data_path: "${oc.env:PREPROCESSED_RTCOR_DIR}/"
x_seq_size: 9
y_seq_size: 9
window_size: 8
input_h_w: [256, 256]
use_orig_data: false
undo_prep: true
