batch_size: 16
test_IDs_fn: "/vol/knmimo-nobackup/restore/knmimo/thesis_pelle/data/preprocessed/data_splits/HEAVY_test_202324_avg001mm_6x9y.npy"
#TODO: fill in after 6x9y model is trained
checkpoint_path: "/vol/knmimo-nobackup/users/pkools/thesis-forecasting/Rainformer/results/model_checkpoints/train_rainformer_6x9/best-epoch30-loss7870.6343.ckpt" #TODO: here
data_path: "/vol/knmimo-nobackup/restore/knmimo/thesis_pelle/data/preprocessed/rtcor_prep"
x_seq_size: 6
y_seq_size: 9
window_size: 8
input_h_w: [256, 256]
use_orig_data: false
undo_prep: true
