batch_size: 64
test_IDs_fn: "/vol/knmimo-nobackup/restore/knmimo/thesis_pelle/data/preprocessed/data_splits/LIGHT_test_202324_avg001mm_9x9y.npy"
checkpoint_path: "/vol/knmimo-nobackup/users/pkools/thesis-forecasting/Rainformer/PreTrainModel/model1_1_100.pt"
data_path: "/vol/knmimo-nobackup/restore/knmimo/thesis_pelle/data/preprocessed/rtcor_pretrained_rainformer"
x_seq_size: 9
y_seq_size: 9
window_size: 9
input_h_w: [288, 288]
use_orig_data: false
undo_prep: false
